### ISSUE TITLE
Workflow 

### ISSUE THREAD

**Issue by Biswajitghosh98** [MLH-Fellowship/0.3.1-team-2-gazel#1]
- [x] Use SciMl backend to solve the Differential equation.
- [x] Use JuliaImages to fetch the current frame.
- [x] Map contrast to brightness
- [x] Trigger the controller callback to reach the desired brightness
- [x] Fix coefficients

**Comment by Biswajitghosh98** [comment]
For Solving the PID Equation using SciMl,<br>
These 2 references can be followed : <br>
[The PID Equation](https://www.scilab.org/discrete-time-pid-controller-implementation) and [Discrete Solvers](https://docs.sciml.ai/v1.10/solvers/discrete_solve.html#Recommended-Methods-1)
Also, e at time t can be expressed in terms of u at time t-1, and du/dt at time t-1.
Although we'll have to initialize with some random velocity for t=0, and then let the solver take charge from the next timestep.
@mgautam98 @dnabanita7  Would you like to add anything ?

**Comment by mgautam98** [comment]
While running system commands on Julia it creates cmd/bash object each time when calling it I hope it will not slow down the app. I am looking for alternatives.

**Comment by mgautam98** [comment]
I am using JuliaImages images.jl to convert to HSL and finding avg of brightness channel but can anyone check the gray scale output of the brightness channel to see if its working fine. 

```
using Images, TestImages, LinearAlgebra, ImageView

rgb_img = testimage("lighthouse")
hsl_img = HSL.(rgb_img)
channels = channelview(float.(hsl_img))
brightness = channels[3,:,:]
sum(brightness)/length(brightness)

0.44476214f0
```
I will push the changes after we finalize the structure and merge #3

**Comment by Biswajitghosh98** [comment]
@mgautam98 I'll have a look ASAP

**Comment by Biswajitghosh98** [comment]
Looking at a different approach through this [article](https://www.telescope-optics.net/eye_intensity_response.htm) which I found great .
