### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by mgautam98** [MLH-Fellowship/0.3.1-team-2-gazel#11]
If solver says we can change the value then we need to map the contrast to brightness value

**Comment by mgautam98** [comment]
@dnabanita7  tell me if you need help in this

**Comment by dnabanita7** [comment]
hey check my  PR #24

**Comment by mgautam98** [comment]
Currently, we will only be using linear mapping for brightness later we can do contrast to brightness mapping
