### ISSUE TITLE
Contrast

### ISSUE THREAD

**Issue by mgautam98** [MLH-Fellowship/0.3.1-team-2-gazel#13]
Idea is to get lowest 5% and highest 5% pixels and find the contrast between them

**Comment by Biswajitghosh98** [comment]
Solved in https://github.com/MLH-Fellowship/0.3.1-team-2-gazel/pull/7
I'll just reopen/send another PR to enclose the same in a function

**Comment by mgautam98** [comment]
Okay let's quickly get this issue done
